In [1]:
def cal_dm(atk,df):
    dm = abs(atk-df)
    if dm > 0:
        return dm
    else:
        return 0
    
class player:
    
    def __init__(self,name, ATK, DEF, atk_speed, blood):
        self.ATK = ATK
        self.DEF = DEF
        self.atk_speed = atk_speed
        self.blood = blood
        self.damage = 0
        self.name = name
    def attack(self, comp):
        
        selfDM = cal_dm(comp.ATK, self.DEF)
        compDM = cal_dm(self.ATK, comp.DEF)
        
        selfNumberOfAtk = comp.blood/compDM
        compNumberOfAtk = self.blood/selfDM
        
        selfTimeToDie = compNumberOfAtk*comp.atk_speed
        compTimeToDie = selfNumberOfAtk*self.atk_speed
        
        if selfTimeToDie > compTimeToDie:
            print(f'{self.name} win')   
        elif selfTimeToDie < compTimeToDie:
            print(f'{comp.name} win')
        else:
            print('Die together')

In [2]:
a = player('a',100,50,1,100)
b = player('b',100,50,1,10000)

a.attack(b)

b win


In [3]:
import numpy as np

In [4]:
a = np.zeros(100).reshape(10,10)
b = np.ones(4).reshape(2,2)
a[4:6, 4:6] = b

In [5]:
a + a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 2., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 2., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
a[:3,:5]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
class Canvas:
    def __init__(self, width, height):
        self.width = width
        self.height = height
        self.area = width * height
        
class Sml_rec:
    def __init__(self, width, height, flip, bound):
        
        self.f = flip
        self.bound = bound
        if flip:
            self.width = width
            self.height = height
            self.area = width * height
            self.p1 = np.random.randint(0, bound.height - self.height)
            self.p2 = np.random.randint(0, bound.width - self.width)
        else:
            
            self.width = height
            self.height = width
            self.area = width * height
            self.p1 = np.random.randint(0, bound.height - self.height)
            self.p2 = np.random.randint(0, bound.width - self.width)
            
        self.dna = '{0:08b}'.format(self.p1) + '{0:08b}'.format(self.p2) + f'{self.f}'

        
    
    def it(self):
        a = np.zeros(bound.area).reshape(bound.height,bound.width)
        b = np.ones(self.area).reshape(self.height,self.width)
        a[self.p1:self.p1 + self.height, self.p2:self.p2 + self.width] = b
    
        return a
    
    def xover(self,other):
        par1 = self.dna
        par2 = other.dna
        position1 = np.random.randint(0, len(par1))
        position2 = np.random.randint(0, len(par2))
        
        chd1_dna = par1[:position2] + par2[position1] +  par1[position2+1:]
        chd2_dna = par2[:position1] + par1[position1] +  par2[position1+1:]
        
        chd1 = Sml_rec(int(chd1_dna[:8],2), int(chd1_dna[8:16],2), int(chd1_dna[-1],2), bound)
        chd2 = Sml_rec(int(chd2_dna[:8],2), int(chd2_dna[8:16],2), int(chd2_dna[-1],2), bound)
        return (chd1, chd2)
    
    def mutate(self):
        position = np.random.randint(0, len(self.dna))
        if self.dna[position] == '1':
            self.dna = self.dna[:position] + '1' + self.dna[position+1:]
        else:
            self.dna = self.dna[:position] + '0' + self.dna[position+1:]

In [8]:
bound = Canvas(255,255)

In [9]:
a = Sml_rec(10,5,0,bound)
b = Sml_rec(10,5,0,bound)

In [10]:
ch1, ch2 = a.xover(b)

In [11]:
ch1.it()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [12]:
ch1.dna

'01111101000110000'

In [13]:
ch1.mutate()

In [14]:
ch1.dna

'01111101000110000'